In [32]:
library(readr)
library(dplyr)
library(janitor)
library(stringr)

In [24]:
scraped <- read_csv("data/brfss_export_data/brfss_2014_phr_1_8_11.csv") |> clean_names()
names(scraped)
length(names(scraped))

Rows: 540 Columns: 116
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (115): question, total_yes_percent, total_no_percent, total_doctor_refus...
dbl   (1): area

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  [1] "area"
  [2] "question"
  [3] "total_yes_percent"
  [4] "total_no_percent"
  [5] "total_doctor_refused_when_asked_percent"
  [6] "total_a_doctor_s_office_or_health_maintenance_organization_hmo_percent"
  [7] "total_a_health_department_percent"
  [8] "total_a_hospital_example_inpatient_percent"
  [9] "total_a_school_percent"
 [10] "total_a_senior_recreation_or_community_center_percent"
 [11] "total_a_store_examples_supermarket_drug_store_percent"
 [12] "total_an_emergency_room_percent"
 [13] "total_another_type_of_clinic_or_health_center_example_a_community_health_center_percent"
 [14] "total_received_vaccination_in_canada_mexico_percent"
 [15] "total_workplace_percent"
 [16] "total_some_other_kind_of_place_percent"
 [17] "total_current_percent"
 [18] "total_former_percent"
 [19] "total_never_percent"
 [20] "total_obese_percent"
 [21] "total_overweight_percent"
 [22] "total_normal_percent"
 [23] "total_underweight_percent"
 [24] "total_within_the_past_year_anytime_less_than_12_months_ago_percent"
 [25] "total_within_the_past_2_years_1_year_but_less_than_2_years_ago_percent"
 [26] "total_within_the_past_3_years_2_years_but_less_than_3_years_ago_percent"
 [27] "total_within_the_past_5_years_3_years_but_less_than_5_years_ago_percent"
 [28] "total_5_or_more_years_ago_percent"
 [29] "total_yes_but_female_told_only_during_pregnancy_percent"
 [30] "total_no_pre_diabetes_or_borderline_diabetes_percent"
 [31] "total_yes_only_one_percent"
 [32] "total_more_than_one_percent"
 [33] "total_within_past_year_anytime_less_than_12_months_ago_percent"
 [34] "total_within_past_2_years_1_year_but_less_than_2_years_ago_percent"
 [35] "total_within_past_5_years_2_years_but_less_than_5_years_ago_percent"
 [36] "total_5_or_more_days_percent"
 [37] "total_none_to_less_than_5_days_percent"
 [38] "total_14_or_more_days_percent"
 [39] "total_none_to_less_than_14_days_percent"
 [40] "total_at_home_percent"
 [41] "total_clinic_percent"
 [42] "total_counselling_and_testing_site_percent"
 [43] "total_drug_treatment_facility_percent"
 [44] "total_emergency_room_percent"
 [45] "total_hospital_inpatient_percent"
 [46] "total_jail_or_prison_or_other_correctional_facility_percent"
 [47] "total_private_doctor_or_hmo_percent"
 [48] "total_somewhere_else_percent"
 [49] "total_none_or_less_than_14_days_percent"
 [50] "total_all_percent"
 [51] "total_most_percent"
 [52] "total_some_percent"
 [53] "total_a_little_percent"
 [54] "total_none_percent"
 [55] "total_agree_strongly_percent"
 [56] "total_agree_slightly_percent"
 [57] "total_neither_agree_nor_disagree_percent"
 [58] "total_disagree_slightly_percent"
 [59] "total_disagree_strongly_percent"
 [60] "total_1_to_5_percent"
 [61] "total_6_or_more_but_not_all_percent"
 [62] "total_always_percent"
 [63] "total_nearly_always_percent"
 [64] "total_sometimes_percent"
 [65] "total_seldom_percent"
 [66] "total_never_drive_or_ride_in_a_car_percent"
 [67] "total_current_smoker_every_day_percent"
 [68] "total_current_smoker_some_days_percent"
 [69] "total_former_smoker_percent"
 [70] "total_never_smoker_percent"
 [71] "total_air_pollution_percent"
 [72] "total_crime_percent"
 [73] "total_no_or_unsafe_paths_or_sidewalks_percent"
 [74] "total_no_shops_or_interesting_places_to_go_percent"
 [75] "total_poor_health_percent"
 [76] "total_too_busy_percent"
 [77] "total_too_far_percent"
 [78] "total_too_much_traffic_percent"
 [79] "total_weather_too_hot_or_too_cold_percent"
 [80] "total_other_percent"
 [81] "total_0_minutes_percent"
 [82] "total_1_9_minutes_percent"
 [83] "total_10_29_minutes_percent"
 [84] "total_30_59_minutes_percent"
 [85] "total_60_minutes_percent"
 [86] "total_colonoscopy_percent"
 [87] "total_sigmoidoscopy_percent"
 [88] "total_within_the_past_month_anytime_less_than_1_month_ago_percent"
 [89] "total_within_the_past_year_1_month_but_less_than_12_months_ago_percent"
 [90] "total_2_or_more_years_ago_percent"
 [91] "total_fair_or_poor_health_percent"
 [92] "total_good_or_better_health_percent"
 [93] "total_1_to_4_miles_percent"
 [94] "total_5_to_9_miles_percent"
 [95] "total_10_to_14_miles_percent"
 [96] "total_15_to_20_miles_percent"
 [97] "total_21_to_50_miles_percent"
 [98] "total_more_than_50_miles_percent"
 [99] "total_most_of_the_time_percent"
[100] "total_about_half_the_time_percent"
[101] "total_usually_cannot_find_calorie_information_percent"
[102] "total_within_the_past_5_years_2_years_but_less_than_5_years_ago_percent"
[103] "total_cost_too_much_too_expensive_can_t_afford_percent"
[104] "total_don_t_need_or_want_percent"
[105] "total_too_hard_to_use_don_t_know_how_to_use_percent"
[106] "total_other_specify_percent"
[107] "total_every_day_percent"
[108] "total_some_days_percent"
[109] "total_not_at_all_percent"
[110] "total_less_than_1_hour_percent"
[111] "total_1_hour_percent"
[112] "total_2_hours_percent"
[113] "total_3_hours_percent"
[114] "total_4_hours_percent"
[115] "total_5_hours_or_more_percent"
[116] "total_you_do_not_watch_tv_or_videos_percent"

[1] 116

In [16]:
brfss <- read_csv("data/brfss_all_categories.csv")
names(brfss)

Rows: 391 Columns: 12
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (12): Sheet, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

 [1] "Sheet" "1"     "2"     "3"     "4"     "5"     "6"     "7"     "8"
[10] "9"     "10"    "11"

In [31]:
scraped[c("question")]

    question
1   Ever Had Hepatitis B Shot
2   Ever Had HPV Shot
3   Ever Had Meningitis Shot
4   Ever Had Pneumonia Shot
5   Ever Had Pneumonia Shot, Age 65+
6   Flu Shot in the Past Year
7   Flu Shot in the Past Year, Age 18-64
8   Flu Shot in the Past Year, Age 65+
9   Had All Hepatitis B Shots
10  Had All HPV Shots
11  Had Shingles Shot, Age 50+
12  Location of Flu Shot
13  Number of Hepatitis B Shots
14  Number of HPV Shots
15  Received Tetanus Shot Since 2005
16  Any Drinking in the Past Month
17  Binge Drinking in the Past Month
18  Binge Drinking or Heavy Alcohol Consumption, Females Age 18-44
19  Heavy Alcohol Consumption
20  Heavy Alcohol Consumption, Females
21  Heavy Alcohol Consumption, Males
22  Advised To Reduce or Quit Drinking
23  Asked About Binge Drinking
24  Asked in Person or On A Form About Amount of Drinking
25  Asked in Person or On A Form If Drinking Alcohol
26  Offered Advice About Level Of Drinking That Is Harmful
27  Arthritis
28  Asthma Status
29  Current Asthma
30  Current Asthma Status
⋮   ⋮
511 Activity on the Internet: Connect with Family and Friends
512 Activity on the Internet: Education or School-Related
513 Activity on the Internet: Manage Investment
514 Activity on the Internet: Online Banking
515 Activity on the Internet: Other
516 Activity on the Internet: Play Games
517 Activity on the Internet: Read the News/for Entertainment
518 Activity on the Internet: Search for General Information
519 Activity on the Internet: Search for Health Information
520 Activity on the Internet: Send and Receive Email
521 Activity on the Internet: Shopping
522 Activity on the Internet: Social Media
523 Minutes Spent On the Internet Per Week
524 Own a Device That Connects to the Internet
525 Own a Device That Gets Medical Assistance
526 Reason For Not Owning a Device That Connects to the Internet
527 Reason For Not Owning a Device That Gets Medical Assistance
528 Current Smoker
529 Ever Smoked
530 Frequency of Smoking
531 Quit Smoking in the Past Year
532 Smokeless Tobacco Use
533 Smoker Status
534 Time Since Quit Smoking
535 Hours of TV Watching Per Day
536 Served On Active Duty in the United States Armed Forces
537 Main Reason for Not Walking for Transportation
538 Minutes of Walking For Transportation Per Day (On Days Adult Walked)
539 Minutes of Walking For Transportation Per Week
540 Number of Days When Walked for Transportation

In [18]:
brfss[c("Sheet")]

    Sheet
1   A One C - No
2   A One C - Yes
3   Advised to Change Eating Hab - No
4   Advised to Change Eating Hab - Yes
5   Advised to Cut Down Salt - Do not use salt
6   Advised to Cut Down Salt - No
7   Advised to Cut Down Salt - Yes
8   Advised to Exercise - No
9   Advised to Exercise - Yes
10  Advised to Take Med - No
11  Advised to Take Med - Yes
12  All Teeth Removed, 65+ - No
13  All Teeth Removed, 65+ - Yes
14  Alzheimers Care - No
15  Alzheimers Care - Yes
16  Any Cancer - No
17  Any Cancer - Yes
18  Any Drinking Past Month - No
19  Any Drinking Past Month - Yes
20  Arthritis - No
21  Arthritis - Yes
22  Asthma Status - Current
23  Asthma Status - Former
24  Asthma Status - Never
25  BMI 3 Categories - Obese
26  BMI 3 Categories - Overweight
27  BMI 3 Categories - Recommended Range
28  BMI 4 Categories - Obese
29  BMI 4 Categories - Overweight
30  BMI 4 Categories - Recommended Range
⋮   ⋮
362 Smoker Status - Former smoker
363 Smoker Status - Never smoked
364 Stool DNA Past 3 Yrs 50-75 I - No
365 Stool DNA Past 3 Yrs 50-75 I - Yes
366 Stool DNA Past 3 Yrs Age 50- - No
367 Stool DNA Past 3 Yrs Age 50- - Yes
368 Stroke - No
369 Stroke - Yes
370 Suicidal Ideation - No
371 Suicidal Ideation - Yes
372 Suicide Attempt - No
373 Suicide Attempt - Yes
374 Teeth Removed - No
375 Teeth Removed - Yes
376 Transgender - No
377 Transgender - Yes
378 Up-To-Date CRC Scrn 50-75 IA - No
379 Up-To-Date CRC Scrn 50-75 IA - Yes
380 Up-To-Date CRC Scrn Age 50-7 - No
381 Up-To-Date CRC Scrn Age 50-7 - Yes
382 Up-To-Date Cervical Cancer S - No
383 Up-To-Date Cervical Cancer S - Yes
384 Up-To-Date Cervical Cancer S 2 - No
385 Up-To-Date Cervical Cancer S 2 - Yes
386 V Col 5 Yrs 50-75 IA - No
387 V Col 5 Yrs 50-75 IA - Yes
388 V Col 5 Yrs Age 50-75 - No
389 V Col 5 Yrs Age 50-75 - Yes
390 VirtualColonoscopy - No
391 VirtualColonoscopy - Yes

In [ ]:
sheet <- brfss[c("Sheet")]

vector <- sheet[[1]]

dict <- list()

for(j in vector){
    split <- strsplit(j, split = " - ")[[1]]
    
    
    if(length(split) >= 2) {
        key <- split[1]
        value <- split[2]
        
        dict[[key]] <- c(dict[[key]], value)
    }
}

In [ ]:
for( i in range(length(dict))){
    dict[i]
}

In [79]:
head(dict$"A One C")

[1] "No"  "Yes"

In [ ]:
colnames(dict)

NULL

[1] "list"

In [ ]:
print(dict$'A One C')

named list()

[1] "No"  "Yes"

In [ ]:
typeof(dict)

NULL

[1] "list"

In [117]:
typeof(dict[1])

length(dict)
dict[1]

[1] "list"

[1] 158

$`A One C`
[1] "No"  "Yes"

In [118]:
dict

$`A One C`
[1] "No"  "Yes"

$`Advised to Change Eating Hab`
[1] "No"  "Yes"

$`Advised to Cut Down Salt`
[1] "Do not use salt" "No"              "Yes"

$`Advised to Exercise`
[1] "No"  "Yes"

$`Advised to Take Med`
[1] "No"  "Yes"

$`All Teeth Removed, 65+`
[1] "No"  "Yes"

$`Alzheimers Care`
[1] "No"  "Yes"

$`Any Cancer`
[1] "No"  "Yes"

$`Any Drinking Past Month`
[1] "No"  "Yes"

$Arthritis
[1] "No"  "Yes"

$`Asthma Status`
[1] "Current" "Former"  "Never"

$`BMI 3 Categories`
[1] "Obese"             "Overweight"        "Recommended Range"

$`BMI 4 Categories`
[1] "Obese"             "Overweight"        "Recommended Range"
[4] "Underweight"

$`BMI 5 Categories`
[1] "Extremely Obese"   "Obese"             "Overweight"
[4] "Recommended Range" "Underweight"

$`BP Location`
[1] "At home"                           "Do not check it"
[3] "On a machine at pharmacy or store"

$`BP Sharing`
[1] "Do Not Share"          "Email, Portal, or Fax" "In Person"
[4] "Telephone"

$`Binge Drinking`
[1] "No"  "Yes"

$`Binge-Heavy Drinking`
[1] "Femal" "Femal"

$Blind
[1] "No"  "Yes"

$COPD
[1] "No"  "Yes"

$CVD
[1] "No"  "Yes"

$`Cervical Cancer Screening`
[1] "No"  "Yes"

$`Cervical Cancer Screening HP`
[1] "No"  "Yes"

$`Cervical Cancer Screening Pa`
[1] "No"  "Yes"

$`Chest CT or CAT Scan`
[1] "No"  "Yes"

$ClnscpySgmscpy
[1] "Both"          "Colonoscopy"   "Sigmoidoscopy"

$`Cog Decline Discuss`
[1] "No"  "Yes"

$`Cog Decline Worry`
[1] "No"  "Yes"

$`Col Past 10 Yrs 50-75`
[1] "No"  "Yes"

$`Col Past 10 Yrs 50-75 IA`
[1] "No"  "Yes"

$`Coronary Heart Disease`
[1] "No"  "Yes"

$`Current Asthma`
[1] "No"  "Yes"

$`Current Asthma 2`
[1] "No"  "Yes"

$`Current E-cig User`
[1] "No"  "Yes"

$`Current Smoker`
[1] "No"  "Yes"

$Deaf
[1] "No"  "Yes"

$`Dentist Visit Past Year`
[1] "No"  "Yes"

$`Depressive Disorder`
[1] "No"  "Yes"

$Diabetes
[1] "No"                              "No, borderline\nor pre-diabetes"
[3] "Yes"                             "Yes, but during pregnancy"

$`Diabetes Affected Feet`
[1] "No"  "Yes"

$`Diabetes Age`
[1] "40 years or younger" "41 to 64"            "65 years or older"

$`Diabetes Education`
[1] "No"  "Yes"

$`Diabetes Eye Exam`
[1] "2 or more years"         "Never"
[3] "Within the past 2 years" "Within the past month"
[5] "Within the past year"

$`Diabetes Status`
[1] "No"  "Yes"

$`Diabetes Test`
[1] "No"  "Yes"

$`Diabetes Type`
[1] "Type 1" "Type 2"

$`Difficulty Concentrating`
[1] "No"  "Yes"

$`Difficulty Doing Errands Alo`
[1] "No"  "Yes"

$`Difficulty Dressing`
[1] "No"  "Yes"

$`Difficulty Walking`
[1] "No"  "Yes"

$`Disability Status`
[1] "No"  "Yes"

$`Dr Rx Pain Talk`
[1] "No"  "Yes"

$DurationClnscpySgmy
[1] "5 or more years ago"     "Within the past 2 years"
[3] "Within the past 3 years" "Within the past 5 years"
[5] "Within the past year"

$DurationHomeBloodStoolTest
[1] "5 or more years ago"     "Within the past 2 years"
[3] "Within the past 3 years" "Within the past 5 years"
[5] "Within the past year"

$`E-Cig Ever`
[1] "Every day"               "Never used e-cigarettes"
[3] "Not at all (right now)"  "Some days"

$`E-Cig Status`
[1] "Current e-cig user" "Current e-cig user" "Former e-cig user"
[4] "Never used e-cigs"

$`Ever Had Blood Stool Test`
[1] "No"  "Yes"

$`Ever Had HIV Test`
[1] "No"  "Yes"

$`Ever Had Sgmscpy-clnscpy`
[1] "No"  "Yes"

$`Ever Smoked`
[1] "No"  "Yes"

$`Ever Told High BP`
[1] "No"                              "No, borderline\nor pre-diabetes"
[3] "Yes"                             "Yes, but during pregnancy"

$`FOBT Past Yr`
[1] "No"  "Yes"

$`FOBT Past Yr IA`
[1] "No"  "Yes"

$`Fair or Poor Health`
[1] "Fair or Poor Health"   "Good or Better Health"

$`Flu Shot in Past Year`
[1] "No"  "Yes"

$`Flu Shot, 18-64`
[1] "No"  "Yes"

$`Flu Shot, 65+`
[1] "No"  "Yes"

$`Flu Vaccine Location`
 [1] "Canada\nMexico"
 [2] "Clinic\nHealth center"
 [3] "Doctor's office\nHMO"
 [4] "Emergency room"
 [5] "Health department"
 [6] "Hospital"
 [7] "Other"
 [8] "School"
 [9] "Senior\nRecreation\nCommunity center"
[10] "Store"
[11] "Workplace"

$`Frequency of Smoking`
[1] "Every day"  "Not at all" "Some days"

$`General Health`
[1] "Excellent" "Fair"      "Good"      "Poor"      "Very Good"

$`Given Up Day-to-Day Activiti`
[1] "Always"    "Never"     "Rarely"    "Sometimes" "Usually"

$`HIV Risk Behavior`
[1] "No"  "Yes"

$`HIV-AIDS Test`
[1] "No"  "Yes"

$`HPV Test Past 5 Yrs 21-65`
[1] "No"  "Yes"

$`HPV Test Past 5 Yrs 21-65 IA`
[1] "No"  "Yes"

$`Have At Least One Personal D`
[1] "No"  "Yes"

$`Health Care Coverage`
[1] "No"  "Yes"

$`Health Care Coverage Age 18-`
[1] "No"  "Yes"

$`Health Care Provider`
[1] "More than one" "No"            "Yes, only one"

$`Heart Attack`
[1] "No"  "Yes"

$`Heart Disease`
[1] "No"  "Yes"

$`Heated TBCO Products`
[1] "No"  "Yes"

$`Heavy Drinking`
[1] "Females" "Females" "Males"   "Males"   "No"      "Yes"

$`Hlth Affected Activ 14+ Days`
[1] "14 or more days"           "None to less than 14 days"

$`Hlth Affected Activ 5+ Days`
[1] "5 or more days"           "None to less than 5 days"

$`Home BP Check`
[1] "No"  "Yes"

$Hysterectomy
[1] "No"  "Yes"

$Insulin
[1] "No"  "Yes"

$`Interfere w Social Act`
[1] "Always"    "Never"     "Rarely"    "Sometimes" "Usually"

$`Kidney Disease`
[1] "No"  "Yes"

$`Last Dentist Visit`
[1] "5 or more years"         "Never"
[3] "Within the past 2 years" "Within the past 5 years"
[5] "Within the past year"

$`Last Smoked`
[1] "10+ years"              "Never smoked regularly" "Within past 10 years"
[4] "Within past 3 months"   "Within past 5 years"    "Within past 6 months"
[7] "Within past month"      "Within past year"

$`Leftover Pain Meds`
[1] "No"  "Yes"

$`Leisure Time PA`
[1] "No"  "Yes"

$`Lifetime Asthma`
[1] "No"  "Yes"

$Mammogram
[1] "No"  "Yes"

$`Mammogram Past 2 Yrs 40+`
[1] "No"  "Yes"

$`Mammogram Past 2 Yrs 40+ IA`
[1] "No"  "Yes"

$`Mammogram Past 2 Yrs 50+`
[1] "No"  "Yes"

$`Mammogram Past 2 Yrs 50+ IA`
[1] "No"  "Yes"

$`Mammogram Past 2 Yrs 50-74`
[1] "No"  "Yes"

$`Mammogram Past 2 Yrs 50-74 I`
[1] "No"  "Yes"

$`Medical Cost`
[1] "No"  "Yes"

$`Memory Loss`
[1] "No"  "Yes"

$`Menthol Cig`
[1] "No"  "Yes"

$`Menthol E-Cig`
[1] "No"  "Yes"

$Obese
[1] "No"  "Yes"

$`Other Cancer`
[1] "No"  "Yes"

$OtherStoolTest
[1] "No"  "Yes"

$`Overweight or Obese`
[1] "No"  "Yes"

$`Pain Med Not Rx`
[1] "No"  "Yes"

$Pap
[1] "HPV Test Past 5 Yrs 21"   "HPV Test Past 5 Yrs 21"
[3] "HPV Test Past 5 Yrs 21 2" "HPV Test Past 5 Yrs 21 2"

$`Pap Test Past 3 Yrs 21-65`
[1] "No"  "Yes"

$`Pap Test Past 3 Yrs 21-65 IA`
[1] "No"  "Yes"

$`Pap Test Past 5 Yrs 21-65`
[1] "No"  "Yes"

$`Pap Test Past 5 Yrs 21-65 IA`
[1] "No"  "Yes"

$`Pneumonia Shot, 18+`
[1] "No"  "Yes"

$`Pneumonia Shot, 65+`
[1] "No"  "Yes"

$`Poor Mental Health 14+ Days`
[1] "14 or more days"           "None to less than 14 days"

$`Poor Mental Health 5+ Days`
[1] "5 or more days"           "None to less than 5 days"

$`Poor Physical Health 14+ Day`
[1] "14 or more days"           "None to less than 14 days"

$`Poor Physical Health 5+ Days`
[1] "5 or more days"           "None to less than 5 days"

$`Pre-Diabetes`
[1] "No"                    "Yes"                   "Yes, during pregnancy"

$`Pre-Diabetes 2`
[1] "No"  "Yes"

$`Provided Care Past 30 Days`
[1] "No"  "Yes"

$`Quit Smoking in Past Yr`
[1] "No"  "Yes"

$`Reg BP Check`
[1] "No"  "Yes"

$RemoveTeeth
[1] "1 to 5"                 "6 or More, but not all" "All"

$`Routine Checkup`
[1] "5 or more years"         "Never"
[3] "Within the past 2 years" "Within the past 5 years"
[5] "Within the past year"

$`Routine Checkup in the Past `
[1] "No"  "Yes"

$`Rx Opioid`
[1] "No"  "Yes"

$`Rx Pain Med`
[1] "No"  "Yes"

$`RxPainRiskEd Source`
[1] "No"  "Yes"

$`Served on Active Duty`
[1] "No"  "Yes"

$SexualOrientation
[1] "Bisexual"       "Lesbian or Gay" "Something Else" "Straight"

$`Sigm Past 10 Yrs 50-75 IA`
[1] "No"  "Yes"

$`Sigm Past 10 Yrs Age 50-75`
[1] "No"  "Yes"

$`Sigm Past 5 Yrs 50-75 IA`
[1] "No"  "Yes"

$`Sigm Past 5 Yrs Age 50-75`
[1] "No"  "Yes"

$`Sigm and Blood Stool 50-75 I`
[1] "No"  "Yes"

$`Sigm and Blood Stool Age 50-`
[1] "No"  "Yes"

$`Skin Cancer`
[1] "No"  "Yes"

$`Smokeless Tobacco Use`
[1] "Every day"  "Not at all" "Some days"

$`Smoker Status`
[1] "Current smoker" "Current smoker" "Former smoker"  "Never smoked"

$`Stool DNA Past 3 Yrs 50-75 I`
[1] "No"  "Yes"

$`Stool DNA Past 3 Yrs Age 50-`
[1] "No"  "Yes"

$Stroke
[1] "No"  "Yes"

$`Suicidal Ideation`
[1] "No"  "Yes"

$`Suicide Attempt`
[1] "No"  "Yes"

$`Teeth Removed`
[1] "No"  "Yes"

$Transgender
[1] "No"  "Yes"

$`Up-To-Date CRC Scrn 50-75 IA`
[1] "No"  "Yes"

$`Up-To-Date CRC Scrn Age 50-7`
[1] "No"  "Yes"

$`Up-To-Date Cervical Cancer S`
[1] "No"  "Yes"

$`Up-To-Date Cervical Cancer S 2`
[1] "No"  "Yes"

$`V Col 5 Yrs 50-75 IA`
[1] "No"  "Yes"

$`V Col 5 Yrs Age 50-75`
[1] "No"  "Yes"

$VirtualColonoscopy
[1] "No"  "Yes"