In [1]:
library(readr)
library(dplyr)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

### Loading model predictors CSVs - Classification

In [2]:
#Classification model - key variables

dtree_vars <- read_csv("data/results/merged_w_svi/important_vars_dtree_phr.csv")

rforest_vars <- read_csv("data/results/merged_w_svi/important_vars_rforest_phr.csv")

boost_vars <- read_csv("data/results/merged_w_svi/important_vars_boost_phr.csv")

boostNA_vars <- read_csv("data/results/merged_w_svi/important_vars_boostNA_phr.csv")

Rows: 22 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): Variable
dbl (1): Importance

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
New names:
• `` -> `...1`
Rows: 180 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): ...1
dbl (4): 0, 1, MeanDecreaseAccuracy, MeanDecreaseGini

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
New names:
• `` -> `...1`
Rows: 49 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): Feature
dbl (4): ...1, Gain, Cover, Frequency

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
New names:
• `` -> `...1`
Rows: 31 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): Feature
dbl (4): ...1, Gain, Cover, Frequency

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

### Loading model predictors CSVs - Regression

In [13]:
rforest_reg_vars <- read_csv("data/results/important_vars_rforest_reg.csv")

New names:
• `` -> `...1`
Rows: 180 Columns: 3
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): ...1
dbl (2): %IncMSE, IncNodePurity

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Dataframe for each model

In [ ]:
#Decision Tree
dtree_vars

   Variable                                             Importance
1  poor_mental_health_14_days_14_or_more_days           62.2651909
2  poor_mental_health_14_days_none_to_less_than_14_days 62.2651909
3  routine_checkup_in_the_past_yes                      50.5519372
4  routine_checkup_within_the_past_year                 50.5519372
5  col_past_10_yrs_50_75_yes                            45.6200408
6  col_past_10_yrs_50_75_ia_yes                         43.1540927
7  ep_otherrace                                         27.0952076
8  pct_black                                            24.9254133
9  disability_status_yes                                12.8647294
10 flu_vaccine_location_doctors_office_hmo              12.8647294
11 health_care_coverage_yes                             12.8647294
12 mammogram_yes                                        12.8647294
13 poor_physical_health_14_day_14_or_more_days          12.8647294
14 enrollment                                            9.0147859
15 ep_munit                                              8.6518823
16 density                                               6.7610894
17 ep_age65                                              6.0098573
18 population                                            6.0098573
19 ep_hburd                                              1.8907929
20 ep_twomore                                            1.8907929
21 pct_uninsured                                         1.8907929
22 ep_disabl                                             0.9453964

In [5]:
#Random Forest
rforest_vars

    ...1                               0           1
1   cve                                 2.823111    6.361563
2   enrollment                          6.953881    9.741782
3   population                          7.180458   10.343315
4   pct_hispanic                        1.040369    8.432247
5   pct_black                           5.637179    9.366988
6   pct_white                          -3.227278    8.176160
7   pct_poverty                        -2.230461    5.669694
8   pct_uninsured                       0.112331    9.761861
9   pct_college                         2.256264    6.540397
10  pct_foreign_born                    5.132714    7.834799
11  advised_to_change_eating_hab_yes    3.699291    2.322932
12  advised_to_cut_down_salt_yes        2.749940    2.631496
13  advised_to_exercise_yes             3.069917    3.155412
14  advised_to_take_med_yes             3.178088    1.982441
15  all_teeth_removed_65_no             2.179642    2.573009
16  any_cancer_yes                      2.642446    2.460976
17  any_drinking_past_month_yes         2.522316    2.306573
18  arthritis_yes                       3.028371    3.296071
19  asthma_status_never                 4.296292    2.717089
20  bmi_3_categories_obese              2.349642    2.057897
21  bmi_3_categories_overweight         3.632207    3.106158
22  bmi_3_categories_recommended_range  2.850067    1.731864
23  bmi_4_categories_obese              2.194368    0.812687
24  bmi_4_categories_overweight         3.527848    3.517989
25  bmi_4_categories_recommended_range  2.485922    1.838896
26  bmi_5_categories_obese              1.360609    1.825403
27  bmi_5_categories_overweight         3.417624    2.935681
28  bmi_5_categories_recommended_range  3.419446    1.983744
29  bp_location_at_home                 2.582292    2.286802
30  bp_sharing_in_person                2.615446    1.859857
⋮   ⋮                                  ⋮           ⋮
151 stool_dna_past_3_yrs_age_50_no      6.19976077  4.233440
152 stroke_no                           3.46130507  2.841522
153 suicidal_ideation_no                3.89478919  4.162084
154 suicide_attempt_no                  2.83980709  2.430248
155 teeth_removed_yes                   2.82622138  1.977263
156 up_to_date_crc_scrn_50_75_ia_yes    3.24322450  2.448972
157 up_to_date_crc_scrn_age_50_7_yes    2.91429282  2.617687
158 v_col_5_yrs_50_75_ia_no             2.51056957  2.055006
159 v_col_5_yrs_age_50_75_no            1.48095630  1.542513
160 virtual_colonoscopy_no              2.29747068  2.076662
161 ep_unemp                            0.53253285  7.224494
162 ep_hburd                            1.03263195  7.786035
163 ep_nohsdp                           2.44621439  7.610839
164 ep_age65                            0.65200945 13.198238
165 ep_age17                            1.51609777  6.974335
166 ep_disabl                          -3.01310905  8.202186
167 ep_sngpnt                           0.69469023  8.924056
168 ep_limeng                          -0.08728828  7.490622
169 ep_munit                            4.98264279 10.407051
170 ep_mobile                          -0.59861877  6.815120
171 ep_crowd                           -0.56996691  8.803819
172 ep_noveh                            0.72184222  7.026265
173 ep_groupq                           0.85397282  6.130094
174 ep_noint                            1.51089166  9.591312
175 ep_asian                            2.81187108  5.682397
176 ep_aian                             4.39243476  9.155082
177 ep_nhpi                             1.93457782  8.319667
178 ep_twomore                          0.28284317  7.626761
179 ep_otherrace                        8.58911303 14.675768
180 density                             7.20012230 10.892675
    MeanDecreaseAccuracy MeanDecreaseGini
1    6.608670            0.72802273
2   10.189184            2.67869050
3   10.744535            2.92759012
4    8.908714            1.21001968
5    9.762897            2.52295655
6    7.502011            1.07231839
7    5.226673            0.43996666
8    9.650978            1.69934748
9    7.058245            1.18855812
10   8.281692            1.35403211
11   3.511437            0.66998870
12   3.078702            0.13557532
13   3.606763            0.30326954
14   2.856091            0.23602033
15   2.979761            0.28146331
16   2.744782            0.31188462
17   2.791609            0.11138117
18   3.864325            0.40993122
19   4.199119            1.18367974
20   2.761133            0.10452737
21   4.271467            0.36066992
22   3.095561            0.44507986
23   2.401068            0.07389436
24   4.080705            0.45453615
25   2.916149            0.38799869
26   1.909400            0.04908087
27   3.865618            0.22464666
28   3.541360            0.88212727
29   2.811021            0.24325622
30   2.824220            0.24112716
⋮   ⋮                    ⋮
151  6.398035            3.9593516
152  3.896973            0.6464425
153  4.947781            0.6433591
154  2.861446            0.2112145
155  3.066643            0.2530868
156  3.259041            0.5061443
157  3.138858            0.5385781
158  2.630753            0.2583323
159  1.872939            0.1232960
160  2.827254            0.3121127
161  7.138804            0.8415829
162  7.870195            1.0514437
163  8.240298            1.0402209
164 13.063474            5.0146754
165  7.045162            0.7549303
166  7.029552            1.2305606
167  8.747056            1.8462623
168  7.214679            0.7650268
169 10.915870            2.2055394
170  5.772042            0.9038520
171  8.491552            1.2939807
172  6.311294            0.7885672
173  6.066159            0.7515064
174  9.297976            1.8895973
175  6.408134            0.5160231
176  9.480621            3.9366777
177  8.031982            1.7345408
178  7.416999            0.7934332
179 14.830638            7.4505855
180 11.413007            3.4515815

In [8]:
#XGBoost
names(boost_vars)
boost_vars

[1] "...1"      "Feature"   "Gain"      "Cover"     "Frequency"

   ...1 Feature                                    Gain         Cover
1   1   poor_mental_health_14_days_14_or_more_days 3.053245e-01 0.115512905
2   2   ep_otherrace                               2.301455e-01 0.157624885
3   3   pct_black                                  5.994472e-02 0.094218451
4   4   stool_dna_past_3_yrs_age_50_no             5.790069e-02 0.055317409
5   5   current_asthma_2_no                        5.196404e-02 0.025384581
6   6   ep_age65                                   4.774467e-02 0.050921945
7   7   enrollment                                 3.103145e-02 0.052482557
8   8   fobt_past_yr_no                            2.212976e-02 0.019054465
9   9   ep_aian                                    2.100828e-02 0.036119021
10 10   cve                                        1.969986e-02 0.062595555
11 11   all_teeth_removed_65_no                    1.853328e-02 0.005292214
12 12   pct_college                                1.733089e-02 0.013213629
13 13   advised_to_change_eating_hab_yes           1.545396e-02 0.004903840
14 14   heated_tbco_products_yes                   1.512892e-02 0.020480742
15 15   general_health_fair                        1.050280e-02 0.013774075
16 16   bmi_3_categories_overweight                1.012394e-02 0.022069276
17 17   ep_asian                                   8.370345e-03 0.025790436
18 18   provided_care_past_30_days_yes             5.571300e-03 0.019111149
19 19   pct_poverty                                5.423744e-03 0.014575902
20 20   ep_nohsdp                                  5.288447e-03 0.010010545
21 21   pct_hispanic                               3.945588e-03 0.029399062
22 22   dentist_visit_past_year_yes                3.944241e-03 0.002444790
23 23   heavy_drinking_males_no                    3.873340e-03 0.009244649
24 24   ep_age17                                   3.672493e-03 0.010680023
25 25   ep_nhpi                                    3.420034e-03 0.009661241
26 26   heavy_drinking_no                          3.374717e-03 0.009768072
27 27   ep_munit                                   3.019095e-03 0.007124397
28 28   density                                    2.627324e-03 0.010417858
29 29   ep_disabl                                  2.001082e-03 0.002972958
30 30   health_care_coverage_yes                   1.983748e-03 0.004431965
31 31   population                                 1.359072e-03 0.012828376
32 32   mammogram_yes                              1.340714e-03 0.005502485
33 33   ever_had_sgmscpy_clnscpy_yes               9.912258e-04 0.005776612
34 34   bmi_3_categories_recommended_range         8.652381e-04 0.005623802
35 35   ep_mobile                                  7.861334e-04 0.007730461
36 36   arthritis_yes                              7.429207e-04 0.001405449
37 37   poor_mental_health_5_days_5_or_more_days   5.733696e-04 0.004752885
38 38   ep_hburd                                   3.435373e-04 0.007057078
39 39   last_dentist_visit_within_the_past_2_years 3.429066e-04 0.007785223
40 40   deaf_no                                    3.285833e-04 0.001245286
41 41   ep_sngpnt                                  3.096671e-04 0.004319333
42 42   ep_groupq                                  3.072725e-04 0.005693028
43 43   last_dentist_visit_within_the_past_5_years 3.064172e-04 0.001390559
44 44   flu_vaccine_location_doctors_office_hmo    2.897688e-04 0.004219217
45 45   ep_noint                                   2.200122e-04 0.003423384
46 46   pct_uninsured                              1.694020e-04 0.001978234
47 47   ep_unemp                                   1.194553e-04 0.001770107
48 48   pct_foreign_born                           6.213918e-05 0.001538525
49 49   dr_rx_pain_talk_yes                        5.940936e-05 0.001361358
   Frequency
1  0.025252525
2  0.080808081
3  0.085858586
4  0.010101010
5  0.005050505
6  0.015151515
7  0.050505051
8  0.005050505
9  0.040404040
10 0.080808081
11 0.005050505
12 0.020202020
13 0.005050505
14 0.005050505
15 0.005050505
16 0.010101010
17 0.055555556
18 0.010101010
19 0.025252525
20 0.020202020
21 0.085858586
22 0.005050505
23 0.015151515
24 0.025252525
25 0.015151515
26 0.005050505
27 0.005050505
28 0.020202020
29 0.005050505
30 0.005050505
31 0.045454545
32 0.010101010
33 0.010101010
34 0.010101010
35 0.020202020
36 0.005050505
37 0.015151515
38 0.025252525
39 0.030303030
40 0.005050505
41 0.015151515
42 0.020202020
43 0.005050505
44 0.005050505
45 0.010101010
46 0.005050505
47 0.005050505
48 0.005050505
49 0.005050505

In [7]:
#XGBoost with NA (phr percent difference included)
boostNA_vars

   ...1 Feature                            Gain         Cover       Frequency
1   1   pct_black                          1.502871e-01 0.062780362 0.076086957
2   2   enrollment                         1.357797e-01 0.079665564 0.054347826
3   3   ep_age65                           1.059503e-01 0.041507085 0.032608696
4   4   pap_hpv_test_past_5_yrs_21_yes     9.975250e-02 0.031049972 0.027173913
5   5   ep_otherrace                       6.569050e-02 0.042791669 0.027173913
6   6   cve                                6.424587e-02 0.090809303 0.081521739
7   7   asthma_status_former               4.517691e-02 0.029459388 0.016304348
8   8   pct_hispanic                       3.921544e-02 0.106344182 0.125000000
9   9   ep_nohsdp                          3.795344e-02 0.028236680 0.016304348
10 10   general_health_good                3.016503e-02 0.022213627 0.010869565
11 11   sigm_and_blood_stool_50_75_i_no    2.835180e-02 0.029627661 0.016304348
12 12   pct_college                        2.441216e-02 0.039485617 0.048913043
13 13   ep_noint                           2.205426e-02 0.027727265 0.032608696
14 14   ep_twomore                         1.969129e-02 0.011742541 0.016304348
15 15   ep_hburd                           1.853020e-02 0.034426947 0.043478261
16 16   ep_age17                           1.789170e-02 0.016808161 0.010869565
17 17   stool_dna_past_3_yrs_age_50_no     1.631531e-02 0.013039698 0.005434783
18 18   population                         1.425247e-02 0.060902914 0.081521739
19 19   ep_asian                           1.333620e-02 0.058081629 0.070652174
20 20   ep_aian                            1.224138e-02 0.042019693 0.048913043
21 21   pct_uninsured                      1.025412e-02 0.038028367 0.043478261
22 22   pct_poverty                        7.856223e-03 0.015180172 0.010869565
23 23   ep_unemp                           5.360351e-03 0.013584613 0.016304348
24 24   pct_foreign_born                   4.748418e-03 0.009979092 0.010869565
25 25   density                            3.117100e-03 0.010103507 0.016304348
26 26   remove_teeth_all                   2.481539e-03 0.006627416 0.005434783
27 27   any_cancer_yes                     2.385123e-03 0.013723076 0.016304348
28 28   ep_sngpnt                          1.522652e-03 0.003528641 0.005434783
29 29   asthma_status_current              5.536624e-04 0.013469500 0.021739130
30 30   bmi_3_categories_recommended_range 3.273706e-04 0.003736610 0.005434783
31 31   ep_disabl                          9.992529e-05 0.003319048 0.005434783

In [14]:
#Random Forest Regression
rforest_reg_vars

    ...1                               %IncMSE     IncNodePurity
1   cve                                -1.2142732  0.8557286033
2   enrollment                          4.8969350  0.4839912366
3   population                          6.5683052  0.5024190140
4   pct_hispanic                        1.6911456  0.2570532207
5   pct_black                           1.9092080  0.1758571766
6   pct_white                           0.4165344  0.2457416317
7   pct_poverty                        -1.8363449  0.2311114131
8   pct_uninsured                      -0.4373159  1.0464037424
9   pct_college                         3.4961393  0.6273607142
10  pct_foreign_born                    1.8671823  0.1398095869
11  advised_to_change_eating_hab_yes   -1.0303131  0.0009555071
12  advised_to_cut_down_salt_yes        0.0000000  0.0000000000
13  advised_to_exercise_yes             1.9332387  0.0083349412
14  advised_to_take_med_yes             1.5191935  0.0050375899
15  all_teeth_removed_65_no             0.4608340  0.0050842061
16  any_cancer_yes                      4.3435416  0.0922669752
17  any_drinking_past_month_yes         0.8341638  0.0007000179
18  arthritis_yes                       1.0538208  0.0037936738
19  asthma_status_never                 2.4039165  0.0637927898
20  bmi_3_categories_obese              2.4681499  0.0602712599
21  bmi_3_categories_overweight         2.1012399  0.0465762489
22  bmi_3_categories_recommended_range  2.1793227  0.0243377181
23  bmi_4_categories_obese              2.1203869  0.0586807559
24  bmi_4_categories_overweight         1.3387641  0.0347177964
25  bmi_4_categories_recommended_range  3.0347622  0.0861595657
26  bmi_5_categories_obese              2.4971917  0.0473365930
27  bmi_5_categories_overweight         2.1170011  0.0173492016
28  bmi_5_categories_recommended_range  3.8073889  0.1053652759
29  bp_location_at_home                -1.4157919  0.0029319890
30  bp_sharing_in_person               -0.6601799  0.0018539586
⋮   ⋮                                  ⋮           ⋮
151 stool_dna_past_3_yrs_age_50_no      1.53024922 6.616490e-03
152 stroke_no                           1.02609684 3.816262e-04
153 suicidal_ideation_no                1.14572562 5.406687e-02
154 suicide_attempt_no                  0.00000000 1.982541e-20
155 teeth_removed_yes                   0.27763559 3.758241e-03
156 up_to_date_crc_scrn_50_75_ia_yes   -1.00071505 5.088065e-03
157 up_to_date_crc_scrn_age_50_7_yes   -1.00071505 1.004112e-04
158 v_col_5_yrs_50_75_ia_no             1.00071505 5.955357e-06
159 v_col_5_yrs_age_50_75_no            0.00000000 0.000000e+00
160 virtual_colonoscopy_no              0.59181776 1.859247e-03
161 ep_unemp                           -0.52566119 1.357659e-01
162 ep_hburd                            3.70996735 1.018402e+00
163 ep_nohsdp                           4.55813545 1.041646e+00
164 ep_age65                            4.83926736 8.108008e-01
165 ep_age17                           -1.02504356 1.014277e+00
166 ep_disabl                           0.56744587 1.467473e-01
167 ep_sngpnt                          -0.50902462 1.030257e-01
168 ep_limeng                           0.73554093 1.692868e-01
169 ep_munit                            4.56525021 3.695443e-01
170 ep_mobile                           3.28857379 3.182137e-01
171 ep_crowd                            0.63950354 9.501517e-02
172 ep_noveh                            0.59683769 1.974029e-01
173 ep_groupq                          -0.94597274 1.690655e-01
174 ep_noint                            0.94744737 1.410998e-01
175 ep_asian                           -1.25332535 1.756397e-01
176 ep_aian                             0.56959768 7.970882e-02
177 ep_nhpi                            -1.14334801 3.794176e-02
178 ep_twomore                          0.08537336 1.050662e-01
179 ep_otherrace                        3.66464889 2.349404e-01
180 density                             4.97944545 3.759290e-01

### Finding Common Predictors among the models

In [23]:
#common predictors among all models - Classification

#grabing the columns of each dataframe that contain the predictors
dtree <- dtree_vars |> pull(1)
rforest <- rforest_vars |> pull(1)
boost <- boost_vars |> pull(2)
boost_NA <- boostNA_vars |> pull(2)
rforest_reg <- rforest_reg_vars |> pull(1)

#creates a list of all the predictors from all the dataframes; used to find common predictors later
all_vars <- list(dtree, rforest, boost, boost_NA, rforest_reg)
common_vars <- Reduce(intersect, all_vars)

print(common_vars)
length(common_vars)

[1] "ep_otherrace"  "pct_black"     "enrollment"    "density"
[5] "ep_age65"      "population"    "ep_hburd"      "pct_uninsured"
[9] "ep_disabl"

[1] 9

In [22]:
rforest <- rforest_vars |> pull(1)
rforest_reg <- rforest_reg_vars |> pull(1)

all_vars <- list(rforest, rforest_reg)
common_rf <- Reduce(intersect, all_vars )


diff <- setdiff(union(rforest, rforest_reg), intersect(rforest, rforest_reg))
length(diff)

common_rf
length(common_rf)

[1] 0

  [1] "cve"
  [2] "enrollment"
  [3] "population"
  [4] "pct_hispanic"
  [5] "pct_black"
  [6] "pct_white"
  [7] "pct_poverty"
  [8] "pct_uninsured"
  [9] "pct_college"
 [10] "pct_foreign_born"
 [11] "advised_to_change_eating_hab_yes"
 [12] "advised_to_cut_down_salt_yes"
 [13] "advised_to_exercise_yes"
 [14] "advised_to_take_med_yes"
 [15] "all_teeth_removed_65_no"
 [16] "any_cancer_yes"
 [17] "any_drinking_past_month_yes"
 [18] "arthritis_yes"
 [19] "asthma_status_never"
 [20] "bmi_3_categories_obese"
 [21] "bmi_3_categories_overweight"
 [22] "bmi_3_categories_recommended_range"
 [23] "bmi_4_categories_obese"
 [24] "bmi_4_categories_overweight"
 [25] "bmi_4_categories_recommended_range"
 [26] "bmi_5_categories_obese"
 [27] "bmi_5_categories_overweight"
 [28] "bmi_5_categories_recommended_range"
 [29] "bp_location_at_home"
 [30] "bp_sharing_in_person"
 [31] "binge_drinking_yes"
 [32] "blind_no"
 [33] "copd_no"
 [34] "cvd_no"
 [35] "cervical_cancer_screening_yes"
 [36] "cervical_cancer_screening_hp_yes"
 [37] "cervical_cancer_screening_pa_yes"
 [38] "chest_ct_or_cat_scan_yes"
 [39] "clnscpy_sgmscpy_colonoscopy"
 [40] "col_past_10_yrs_50_75_yes"
 [41] "col_past_10_yrs_50_75_ia_yes"
 [42] "coronary_heart_disease_no"
 [43] "current_asthma_2_no"
 [44] "current_e_cig_user_yes"
 [45] "current_smoker_yes"
 [46] "deaf_no"
 [47] "dentist_visit_past_year_yes"
 [48] "depressive_disorder_yes"
 [49] "diabetes_yes"
 [50] "diabetes_status_yes"
 [51] "difficulty_concentrating_yes"
 [52] "difficulty_doing_errands_alo_no"
 [53] "difficulty_dressing_no"
 [54] "difficulty_walking_yes"
 [55] "disability_status_yes"
 [56] "dr_rx_pain_talk_yes"
 [57] "ever_had_blood_stool_test_yes"
 [58] "ever_had_hiv_test_yes"
 [59] "ever_had_sgmscpy_clnscpy_yes"
 [60] "ever_smoked_yes"
 [61] "ever_told_high_bp_yes"
 [62] "fobt_past_yr_no"
 [63] "fobt_past_yr_ia_no"
 [64] "fair_or_poor_health_fair_or_poor_health"
 [65] "fair_or_poor_health_good_or_better_health"
 [66] "flu_shot_in_past_year_yes"
 [67] "flu_shot_18_64_yes"
 [68] "flu_shot_65_yes"
 [69] "flu_vaccine_location_doctors_office_hmo"
 [70] "flu_vaccine_location_store"
 [71] "frequency_of_smoking_every_day"
 [72] "frequency_of_smoking_not_at_all"
 [73] "general_health_excellent"
 [74] "general_health_fair"
 [75] "general_health_good"
 [76] "general_health_very_good"
 [77] "hiv_risk_behavior_no"
 [78] "hiv_aids_test_yes"
 [79] "have_at_least_one_personal_d_yes"
 [80] "health_care_coverage_yes"
 [81] "health_care_coverage_age_18_yes"
 [82] "health_care_provider_more_than_one"
 [83] "health_care_provider_no"
 [84] "health_care_provider_yes_only_one"
 [85] "heart_attack_no"
 [86] "heart_disease_no"
 [87] "heated_tbco_products_yes"
 [88] "heavy_drinking_females_no"
 [89] "heavy_drinking_males_no"
 [90] "heavy_drinking_no"
 [91] "hlth_affected_activ_14_days_14_or_more_days"
 [92] "hlth_affected_activ_14_days_none_to_less_than_14_days"
 [93] "hlth_affected_activ_5_days_5_or_more_days"
 [94] "hlth_affected_activ_5_days_none_to_less_than_5_days"
 [95] "home_bp_check_yes"
 [96] "hysterectomy_yes"
 [97] "kidney_disease_no"
 [98] "last_dentist_visit_5_or_more_years"
 [99] "last_dentist_visit_within_the_past_2_years"
[100] "last_dentist_visit_within_the_past_5_years"
[101] "last_dentist_visit_within_the_past_year"
[102] "last_smoked_10_years"
[103] "leisure_time_pa_yes"
[104] "lifetime_asthma_yes"
[105] "mammogram_yes"
[106] "mammogram_past_2_yrs_40_yes"
[107] "mammogram_past_2_yrs_40_ia_yes"
[108] "mammogram_past_2_yrs_50_yes"
[109] "mammogram_past_2_yrs_50_ia_yes"
[110] "mammogram_past_2_yrs_50_74_yes"
[111] "mammogram_past_2_yrs_50_74_i_yes"
[112] "medical_cost_yes"
[113] "memory_loss_no"
[114] "obese_yes"
[115] "other_cancer_no"
[116] "overweight_or_obese_yes"
[117] "pain_med_not_rx_no"
[118] "pneumonia_shot_18_yes"
[119] "pneumonia_shot_65_yes"
[120] "poor_mental_health_14_days_14_or_more_days"
[121] "poor_mental_health_14_days_none_to_less_than_14_days"
[122] "poor_mental_health_5_days_5_or_more_days"
[123] "poor_mental_health_5_days_none_to_less_than_5_days"
[124] "poor_physical_health_14_day_14_or_more_days"
[125] "poor_physical_health_14_day_none_to_less_than_14_days"
[126] "poor_physical_health_5_days_5_or_more_days"
[127] "poor_physical_health_5_days_none_to_less_than_5_days"
[128] "pre_diabetes_yes"
[129] "pre_diabetes_2_yes"
[130] "provided_care_past_30_days_yes"
[131] "reg_bp_check_yes"
[132] "remove_teeth_1_to_5"
[133] "remove_teeth_6_or_more_but_not_all"
[134] "routine_checkup_within_the_past_2_years"
[135] "routine_checkup_within_the_past_year"
[136] "routine_checkup_in_the_past_yes"
[137] "rx_opioid_no"
[138] "rx_pain_med_no"
[139] "rx_pain_risk_ed_source_no"
[140] "served_on_active_duty_yes"
[141] "sexual_orientation_straight"
[142] "sigm_past_10_yrs_50_75_ia_no"
[143] "sigm_past_10_yrs_age_50_75_no"
[144] "sigm_past_5_yrs_50_75_ia_no"
[145] "sigm_past_5_yrs_age_50_75_no"
[146] "skin_cancer_no"
[147] "smokeless_tobacco_use_not_at_all"
[148] "smoker_status_former_smoker"
[149] "smoker_status_never_smoked"
[150] "stool_dna_past_3_yrs_50_75_i_no"
[151] "stool_dna_past_3_yrs_age_50_no"
[152] "stroke_no"
[153] "suicidal_ideation_no"
[154] "suicide_attempt_no"
[155] "teeth_removed_yes"
[156] "up_to_date_crc_scrn_50_75_ia_yes"
[157] "up_to_date_crc_scrn_age_50_7_yes"
[158] "v_col_5_yrs_50_75_ia_no"
[159] "v_col_5_yrs_age_50_75_no"
[160] "virtual_colonoscopy_no"
[161] "ep_unemp"
[162] "ep_hburd"
[163] "ep_nohsdp"
[164] "ep_age65"
[165] "ep_age17"
[166] "ep_disabl"
[167] "ep_sngpnt"
[168] "ep_limeng"
[169] "ep_munit"
[170] "ep_mobile"
[171] "ep_crowd"
[172] "ep_noveh"
[173] "ep_groupq"
[174] "ep_noint"
[175] "ep_asian"
[176] "ep_aian"
[177] "ep_nhpi"
[178] "ep_twomore"
[179] "ep_otherrace"
[180] "density"

[1] 180

In [ ]:
#common predictors between dtree and rforest
dtree <- dtree_vars |> pull(1)
rforest <- rforest_vars |> pull(1)

dec_for_common <- intersect(dtree, rforest)
dec_for_common
length(dec_for_common)

 [1] "mammogram_no"
 [2] "mammogram_yes"
 [3] "flu_vaccine_location_doctors_office_hmo"
 [4] "have_at_least_one_personal_d_no"
 [5] "have_at_least_one_personal_d_yes"
 [6] "health_care_provider_no"
 [7] "pct_black"
 [8] "ep_munit"
 [9] "ep_age65"
[10] "ep_twomore"
[11] "density"
[12] "ep_crowd"
[13] "cve"
[14] "ep_hburd"
[15] "pct_foreign_born"
[16] "ep_age17"
[17] "ep_disabl"

[1] 17

In [ ]:
#common predictors between boost and boost with NAs
boost <- boost_vars |> pull(2)
boost_NA <- boost_vars_NA |> pull(2)

boost_common_vars <- intersect(boost, boost_NA)
boost_common_vars
length(boost_common_vars)

 [1] "mammogram_no"                  "pct_black"
 [3] "ep_otherrace"                  "density"
 [5] "ep_age65"                      "ep_unemp"
 [7] "ep_munit"                      "ep_aian"
 [9] "cve"                           "ep_groupq"
[11] "population"                    "pct_uninsured"
[13] "ep_noint"                      "ep_age17"
[15] "general_health_good"           "ep_nohsdp"
[17] "provided_care_past_30_days_no" "ep_twomore"
[19] "pct_hispanic"                  "ep_asian"
[21] "any_cancer_no"                 "ep_mobile"
[23] "ep_limeng"

[1] 23

In [ ]:
dtree_vars_vec <- c(dtree_vars$Variable)
print("dtree predictors")
dtree_vars_vec

rforest_vars_vec <- c(rforest_vars$...1)
print("rforest predictors")
rforest_vars_vec

boost_vars_vec <- c(boost_vars$Feature)
print("boost predictors")
boost_vars_vec

boost_vars_NA_vec <- c(boost_vars_NA$Feature)
print("boost w NAs predictors")
boost_vars_NA_vec

[1] "dtree predictors"

 [1] "mammogram_no"
 [2] "mammogram_yes"
 [3] "flu_vaccine_location_doctors_office_hmo"
 [4] "have_at_least_one_personal_d_no"
 [5] "have_at_least_one_personal_d_yes"
 [6] "health_care_provider_no"
 [7] "pct_black"
 [8] "ep_munit"
 [9] "ep_age65"
[10] "ep_twomore"
[11] "density"
[12] "ep_crowd"
[13] "cve"
[14] "ep_hburd"
[15] "pct_foreign_born"
[16] "ep_age17"
[17] "ep_disabl"

[1] "rforest predictors"

  [1] "cve"
  [2] "population"
  [3] "pct_hispanic"
  [4] "pct_black"
  [5] "pct_white"
  [6] "pct_poverty"
  [7] "pct_uninsured"
  [8] "pct_college"
  [9] "pct_foreign_born"
 [10] "advised_to_change_eating_hab_no"
 [11] "advised_to_change_eating_hab_yes"
 [12] "advised_to_cut_down_salt_no"
 [13] "advised_to_cut_down_salt_yes"
 [14] "advised_to_exercise_no"
 [15] "advised_to_exercise_yes"
 [16] "advised_to_take_med_yes"
 [17] "all_teeth_removed_65_no"
 [18] "any_cancer_no"
 [19] "any_cancer_yes"
 [20] "any_drinking_past_month_no"
 [21] "any_drinking_past_month_yes"
 [22] "arthritis_no"
 [23] "arthritis_yes"
 [24] "asthma_status_never"
 [25] "bmi_3_categories_obese"
 [26] "bmi_3_categories_overweight"
 [27] "bmi_3_categories_recommended_range"
 [28] "bmi_4_categories_obese"
 [29] "bmi_4_categories_overweight"
 [30] "bmi_4_categories_recommended_range"
 [31] "bmi_5_categories_obese"
 [32] "bmi_5_categories_overweight"
 [33] "bmi_5_categories_recommended_range"
 [34] "bp_location_at_home"
 [35] "bp_sharing_in_person"
 [36] "binge_drinking_no"
 [37] "binge_drinking_yes"
 [38] "blind_no"
 [39] "copd_no"
 [40] "cvd_no"
 [41] "cervical_cancer_screening_no"
 [42] "cervical_cancer_screening_yes"
 [43] "cervical_cancer_screening_hp_no"
 [44] "cervical_cancer_screening_hp_yes"
 [45] "cervical_cancer_screening_pa_yes"
 [46] "chest_ct_or_cat_scan_no"
 [47] "chest_ct_or_cat_scan_yes"
 [48] "clnscpy_sgmscpy_colonoscopy"
 [49] "col_past_10_yrs_50_75_no"
 [50] "col_past_10_yrs_50_75_yes"
 [51] "col_past_10_yrs_50_75_ia_no"
 [52] "col_past_10_yrs_50_75_ia_yes"
 [53] "coronary_heart_disease_no"
 [54] "current_asthma_2_no"
 [55] "current_e_cig_user_no"
 [56] "current_e_cig_user_yes"
 [57] "current_smoker_no"
 [58] "current_smoker_yes"
 [59] "deaf_no"
 [60] "dentist_visit_past_year_no"
 [61] "dentist_visit_past_year_yes"
 [62] "depressive_disorder_no"
 [63] "depressive_disorder_yes"
 [64] "diabetes_no"
 [65] "diabetes_yes"
 [66] "diabetes_status_no"
 [67] "diabetes_status_yes"
 [68] "difficulty_concentrating_no"
 [69] "difficulty_concentrating_yes"
 [70] "difficulty_doing_errands_alo_no"
 [71] "difficulty_dressing_no"
 [72] "difficulty_walking_no"
 [73] "difficulty_walking_yes"
 [74] "disability_status_no"
 [75] "disability_status_yes"
 [76] "dr_rx_pain_talk_yes"
 [77] "ever_had_blood_stool_test_yes"
 [78] "ever_had_hiv_test_no"
 [79] "ever_had_hiv_test_yes"
 [80] "ever_had_sgmscpy_clnscpy_no"
 [81] "ever_had_sgmscpy_clnscpy_yes"
 [82] "ever_smoked_no"
 [83] "ever_smoked_yes"
 [84] "ever_told_high_bp_no"
 [85] "ever_told_high_bp_yes"
 [86] "fobt_past_yr_no"
 [87] "fobt_past_yr_ia_no"
 [88] "fair_or_poor_health_fair_or_poor_health"
 [89] "fair_or_poor_health_good_or_better_health"
 [90] "flu_shot_in_past_year_no"
 [91] "flu_shot_in_past_year_yes"
 [92] "flu_shot_18_64_no"
 [93] "flu_shot_18_64_yes"
 [94] "flu_shot_65_no"
 [95] "flu_shot_65_yes"
 [96] "flu_vaccine_location_doctors_office_hmo"
 [97] "flu_vaccine_location_store"
 [98] "frequency_of_smoking_every_day"
 [99] "frequency_of_smoking_not_at_all"
[100] "general_health_excellent"
[101] "general_health_fair"
[102] "general_health_good"
[103] "general_health_very_good"
[104] "hiv_risk_behavior_no"
[105] "hiv_aids_test_no"
[106] "hiv_aids_test_yes"
[107] "have_at_least_one_personal_d_no"
[108] "have_at_least_one_personal_d_yes"
[109] "health_care_coverage_no"
[110] "health_care_coverage_yes"
[111] "health_care_coverage_age_18_no"
[112] "health_care_coverage_age_18_yes"
[113] "health_care_provider_more_than_one"
[114] "health_care_provider_no"
[115] "health_care_provider_yes_only_one"
[116] "heart_attack_no"
[117] "heart_disease_no"
[118] "heated_tbco_products_no"
[119] "heated_tbco_products_yes"
[120] "heavy_drinking_females_no"
[121] "heavy_drinking_males_no"
[122] "heavy_drinking_no"
[123] "hlth_affected_activ_14_days_14_or_more_days"
[124] "hlth_affected_activ_14_days_none_to_less_than_14_days"
[125] "hlth_affected_activ_5_days_5_or_more_days"
[126] "hlth_affected_activ_5_days_none_to_less_than_5_days"
[127] "home_bp_check_yes"
[128] "hysterectomy_no"
[129] "hysterectomy_yes"
[130] "kidney_disease_no"
[131] "last_dentist_visit_5_or_more_years"
[132] "last_dentist_visit_within_the_past_2_years"
[133] "last_dentist_visit_within_the_past_5_years"
[134] "last_dentist_visit_within_the_past_year"
[135] "last_smoked_10_years"
[136] "leisure_time_pa_no"
[137] "leisure_time_pa_yes"
[138] "lifetime_asthma_no"
[139] "lifetime_asthma_yes"
[140] "mammogram_no"
[141] "mammogram_yes"
[142] "mammogram_past_2_yrs_40_no"
[143] "mammogram_past_2_yrs_40_yes"
[144] "mammogram_past_2_yrs_40_ia_no"
[145] "mammogram_past_2_yrs_40_ia_yes"
[146] "mammogram_past_2_yrs_50_no"
[147] "mammogram_past_2_yrs_50_yes"
[148] "mammogram_past_2_yrs_50_ia_no"
[149] "mammogram_past_2_yrs_50_ia_yes"
[150] "mammogram_past_2_yrs_50_74_yes"
[151] "mammogram_past_2_yrs_50_74_i_yes"
[152] "medical_cost_no"
[153] "medical_cost_yes"
[154] "memory_loss_no"
[155] "obese_no"
[156] "obese_yes"
[157] "other_cancer_no"
[158] "overweight_or_obese_no"
[159] "overweight_or_obese_yes"
[160] "pain_med_not_rx_no"
[161] "pneumonia_shot_18_no"
[162] "pneumonia_shot_18_yes"
[163] "pneumonia_shot_65_no"
[164] "pneumonia_shot_65_yes"
[165] "poor_mental_health_14_days_14_or_more_days"
[166] "poor_mental_health_14_days_none_to_less_than_14_days"
[167] "poor_mental_health_5_days_5_or_more_days"
[168] "poor_mental_health_5_days_none_to_less_than_5_days"
[169] "poor_physical_health_14_day_14_or_more_days"
[170] "poor_physical_health_14_day_none_to_less_than_14_days"
[171] "poor_physical_health_5_days_5_or_more_days"
[172] "poor_physical_health_5_days_none_to_less_than_5_days"
[173] "pre_diabetes_no"
[174] "pre_diabetes_yes"
[175] "pre_diabetes_2_no"
[176] "pre_diabetes_2_yes"
[177] "provided_care_past_30_days_no"
[178] "provided_care_past_30_days_yes"
[179] "reg_bp_check_no"
[180] "reg_bp_check_yes"
[181] "remove_teeth_1_to_5"
[182] "remove_teeth_6_or_more_but_not_all"
[183] "routine_checkup_within_the_past_2_years"
[184] "routine_checkup_within_the_past_year"
[185] "routine_checkup_in_the_past_no"
[186] "routine_checkup_in_the_past_yes"
[187] "rx_opioid_no"
[188] "rx_pain_med_no"
[189] "rx_pain_risk_ed_source_no"
[190] "served_on_active_duty_no"
[191] "served_on_active_duty_yes"
[192] "sexual_orientation_straight"
[193] "sigm_past_10_yrs_50_75_ia_no"
[194] "sigm_past_10_yrs_age_50_75_no"
[195] "sigm_past_5_yrs_50_75_ia_no"
[196] "sigm_past_5_yrs_age_50_75_no"
[197] "skin_cancer_no"
[198] "smokeless_tobacco_use_not_at_all"
[199] "smoker_status_former_smoker"
[200] "smoker_status_never_smoked"
[201] "stool_dna_past_3_yrs_50_75_i_no"
[202] "stool_dna_past_3_yrs_age_50_no"
[203] "stroke_no"
[204] "suicidal_ideation_no"
[205] "suicide_attempt_no"
[206] "teeth_removed_no"
[207] "teeth_removed_yes"
[208] "up_to_date_crc_scrn_50_75_ia_no"
[209] "up_to_date_crc_scrn_50_75_ia_yes"
[210] "up_to_date_crc_scrn_age_50_7_no"
[211] "up_to_date_crc_scrn_age_50_7_yes"
[212] "v_col_5_yrs_50_75_ia_no"
[213] "v_col_5_yrs_age_50_75_no"
[214] "virtual_colonoscopy_no"
[215] "ep_unemp"
[216] "ep_hburd"
[217] "ep_nohsdp"
[218] "ep_age65"
[219] "ep_age17"
[220] "ep_disabl"
[221] "ep_sngpnt"
[222] "ep_limeng"
[223] "ep_munit"
[224] "ep_mobile"
[225] "ep_crowd"
[226] "ep_noveh"
[227] "ep_groupq"
[228] "ep_noint"
[229] "ep_asian"
[230] "ep_aian"
[231] "ep_nhpi"
[232] "ep_twomore"
[233] "ep_otherrace"
[234] "density"

[1] "boost predictors"

 [1] "mammogram_no"
 [2] "pct_black"
 [3] "ep_otherrace"
 [4] "poor_mental_health_14_days_14_or_more_days"
 [5] "density"
 [6] "advised_to_change_eating_hab_no"
 [7] "ep_age65"
 [8] "ep_unemp"
 [9] "ep_munit"
[10] "ep_aian"
[11] "cve"
[12] "general_health_excellent"
[13] "ep_groupq"
[14] "population"
[15] "ep_hburd"
[16] "mammogram_past_2_yrs_50_74_yes"
[17] "pct_uninsured"
[18] "ep_noint"
[19] "ep_age17"
[20] "pct_college"
[21] "general_health_good"
[22] "ep_nohsdp"
[23] "sigm_past_5_yrs_50_75_ia_no"
[24] "provided_care_past_30_days_no"
[25] "ep_crowd"
[26] "current_e_cig_user_no"
[27] "ep_twomore"
[28] "pct_hispanic"
[29] "ep_asian"
[30] "any_cancer_no"
[31] "poor_physical_health_14_day_14_or_more_days"
[32] "ep_noveh"
[33] "ep_mobile"
[34] "mammogram_past_2_yrs_50_ia_no"
[35] "lifetime_asthma_no"
[36] "pain_med_not_rx_no"
[37] "ep_sngpnt"
[38] "ep_nhpi"
[39] "heart_attack_no"
[40] "mammogram_past_2_yrs_40_ia_no"
[41] "ep_limeng"
[42] "chest_ct_or_cat_scan_no"
[43] "reg_bp_check_no"

[1] "boost w NAs predictors"

 [1] "pap_hpv_test_past_5_yrs_21_no"      "cve"
 [3] "ep_age65"                           "pct_black"
 [5] "ep_aian"                            "enrollment"
 [7] "ep_unemp"                           "pct_hispanic"
 [9] "ep_groupq"                          "ep_otherrace"
[11] "pct_uninsured"                      "general_health_good"
[13] "ep_age17"                           "provided_care_past_30_days_no"
[15] "ep_munit"                           "any_cancer_no"
[17] "population"                         "density"
[19] "mammogram_no"                       "ep_nohsdp"
[21] "pct_foreign_born"                   "pct_poverty"
[23] "ep_mobile"                          "ep_noint"
[25] "ep_asian"                           "ep_twomore"
[27] "bmi_3_categories_recommended_range" "ep_limeng"
[29] "pct_white"

In [ ]:
print("boost length")
length(boost_vars_vec)

print("boost NA length")
length(boost_vars_NA_vec)

[1] "boost length"

[1] 43

[1] "boost NA length"

[1] 29